name:                LambdaJS
version:             1.2
copyright:           Copyright (c) 2009--2012 Brown University and Claudiu Saftoiu
license:             BSD3
category:            Language
license-file:   ../LICENSE
author:         Arjun Guha, Claudiu Saftoiu
maintainer:     Arjun Guha <arjun@cs.brown.edu>
homepage:       http://www.cs.brown.edu/~arjun/
synopsis:       Compiler from JavaScript to LambdaJS.

dependencies:
   - base >= 4 && < 5
   - mtl >= 1.1.0.1
   - parsec >= 3.0.0
   - pretty >= 0.1
   - containers >= 0.1
   - syb >= 0.1
   - language-ecmascript

library:
  source-dirs:
    - src

  ghc-options: -Wall




# Executable lambdaJS
#   Main-Is: LambdaJS.hs
#   Hs-Source-Dirs: src
#   Build-Depends:
#     base >= 4 && < 5,
#     mtl >= 1.1.0.1,
#     parsec >= 3.0.0,
#     pretty >= 0.1, 
#     containers >= 0.1,
#     syb >= 0.1,
#     language-ecmascript
#   ghc-options:
#     -fwarn-incomplete-patterns -rtsopts
#   Extensions:     
#     DeriveDataTypeable Rank2Types FlexibleInstances
